# Generated by Django 5.1.7 on 2025-04-06 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0697_empty_topic_name_for_dms_from_third_party_imports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debat",
            fields=[
                ("debat_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="", max_length=100)),
                ("creator_email", models.EmailField(max_length=254)),
                ("max_per_group", models.IntegerField()),
                ("end_date", models.DateTimeField()),
                ("time_between_round", models.IntegerField()),
                ("num_pass", models.IntegerField()),
                ("step", models.IntegerField(default=1)),
                ("description", models.TextField(default="")),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("channel_created", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Society", "Society"),
                            ("Politics", "Politics"),
                            ("Science", "Science"),
                            ("Philosophy", "Philosophy"),
                            ("Religion", "Religion"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
