# Generated by Django 5.1.7 on 2025-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0698_debat"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="debat_created",
            field=models.BooleanField(default=False),
        ),
    ]
