# Generated by Django 5.1.7 on 2025-04-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0699_debat_debat_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("participant_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("pseudo", models.CharField(default="", max_length=100)),
                ("is_register", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="debat",
            name="debat_participant",
            field=models.ManyToManyField(to="zerver.participant"),
        ),
    ]
