# Generated by Django 5.1.7 on 2025-07-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0700_participant_debat_debat_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="is_archived",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
