# Generated by Django 5.1.7 on 2025-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0702_debat_criteres"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="age",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="domaine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
