# Generated by Django 5.1.7 on 2025-07-07 08:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0704_remove_debat_criteres"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="criteres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), blank=True, default=list, size=None
            ),
        ),
    ]
