# Generated by Django 5.1.7 on 2025-08-01 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0705_debat_criteres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debat",
            old_name="date",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="debat",
            old_name="end_date",
            new_name="subscription_end_date",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="participant_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="debat",
            name="channel_created",
        ),
        migrations.RemoveField(
            model_name="debat",
            name="creator_email",
        ),
        migrations.RemoveField(
            model_name="debat",
            name="criteres",
        ),
        migrations.RemoveField(
            model_name="debat",
            name="num_pass",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="email",
        ),
        migrations.AddField(
            model_name="debat",
            name="creator_id",
            field=models.ForeignKey(
                blank=True,
                null = True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_debates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="debat",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_representative",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="debat",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="debat",
            name="type",
            field=models.CharField(
                choices=[
                    ("Society", "Society"),
                    ("Politics", "Politics"),
                    ("Science", "Science"),
                    ("Philosophy", "Philosophy"),
                    ("Religion", "Religion"),
                    ("General", "General"),
                ],
                default="General",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_register",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phase", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="zerver.debat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupParticipant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="zerver.group",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_participants",
                        to="zerver.participant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="+", through="zerver.GroupParticipant", to="zerver.participant"
            ),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vote_date", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(blank=True, default="pending", max_length=20, null=True),
                ),
                ("phase", models.IntegerField(default=1)),
                (
                    "group_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote",
                        to="zerver.group",
                    ),
                ),
                (
                    "voted_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_received",
                        to="zerver.participant",
                    ),
                ),
                (
                    "voter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_cast",
                        to="zerver.participant",
                    ),
                ),
            ],
        ),
    ]
