# Generated by Django 5.1.7 on 2025-08-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0706_rename_date_debat_creation_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debat",
            old_name="creator_id",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="group_id",
            new_name="group",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="voter_id",
            new_name="voter",
        ),
    ]
