# Generated by Django 5.1.7 on 2025-08-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0707_rename_creator_id_debat_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debat",
            name="start_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
