# Generated by Django 5.1.7 on 2025-08-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0708_alter_debat_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="is_validated",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="debat",
            name="max_representant",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
