# Generated by Django 5.1.7 on 2025-08-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0709_debat_is_validated_debat_max_representant"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="debat_participants",
            field=models.ManyToManyField(
                blank=True, related_name="debates_participated", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="stream",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="zerver.stream",
            ),
        ),
        migrations.AddField(
            model_name="groupparticipant",
            name="participant_new",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_tour",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_active_in_diapyr",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_registered_to_a_debate",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_representative",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
