# Generated by Django 5.1.7 on 2025-08-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0710_debat_debat_participants_group_stream_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupparticipant",
            name="participant_new",
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="group_participants",
                through="zerver.GroupParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupparticipant",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="zerver.group"),
        ),
        migrations.AlterField(
            model_name="groupparticipant",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted_participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_cast",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
