# Generated by Django 5.1.7 on 2025-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0711_remove_groupparticipant_participant_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_register",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
