# Generated by Django 5.1.7 on 2025-08-11 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0712_userprofile_is_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debat",
            name="debat_participant",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="current_tour",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_active_in_diapyr",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_registered_to_a_debate",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_representative",
        ),
        migrations.AlterField(
            model_name="debat",
            name="debat_participants",
            field=models.ManyToManyField(blank=True, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
