# Generated by Django 5.1.7 on 2025-08-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0713_remove_debat_debat_participant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debat",
            name="debat_participants",
            field=models.ManyToManyField(
                blank=True, related_name="participate_at", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_cast",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
