# Generated by Django 5.1.7 on 2025-08-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0714_alter_debat_debat_participants_alter_vote_voter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debat",
            name="debat_participants",
        ),
    ]
