# Generated by Django 5.1.7 on 2025-08-13 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0715_remove_debat_debat_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_registered_to_a_debate", models.BooleanField(default=False, null=True)),
                ("is_active_in_diapyr", models.BooleanField(default=False, null=True)),
                ("is_representative", models.BooleanField(default=False, null=True)),
                ("current_tour", models.IntegerField(default=None, null=True)),
                (
                    "debat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.debat"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="debat",
            name="debat_participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participate_at",
                through="zerver.Participant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
