# Generated by Django 5.1.7 on 2025-08-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0716_participant_debat_debat_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="debat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debat_participant",
                to="zerver.debat",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
