# Generated by Django 5.1.7 on 2025-08-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0717_alter_participant_debat_alter_participant_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(fields=("user", "debat"), name="unique_participant"),
        ),
    ]
