# Generated by Django 5.1.7 on 2025-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0718_participant_unique_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
