# Generated by Django 5.1.7 on 2025-08-20 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0719_group_group_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="phase",
            new_name="round",
        ),
        migrations.AddField(
            model_name="debat",
            name="diapyr_bot",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diapyr_bot",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="debat",
            name="round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="debat",
            name="skip_pre_registration",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="group_number",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="is_archived",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="current_tour",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="is_active_in_diapyr",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
