# Generated by Django 5.1.7 on 2025-08-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0720_rename_phase_group_round_debat_diapyr_bot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debat",
            name="time_between_round",
        ),
    ]
