# Generated by Django 5.1.7 on 2025-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0721_remove_debat_time_between_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="time_between_round",
            field=models.DurationField(null=True),
        ),
    ]
