# Generated by Django 5.1.7 on 2025-08-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0722_debat_time_between_round"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="phase",
            new_name="round",
        ),
        migrations.AddField(
            model_name="vote",
            name="is_interested",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
