# Generated by Django 5.1.7 on 2025-08-22 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0723_rename_phase_vote_round_vote_is_interested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="voted_participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
