# Generated by Django 5.1.7 on 2025-08-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0724_alter_vote_voted_participant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="is_interested",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="voted_participant",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="voter",
        ),
        migrations.AddField(
            model_name="groupparticipant",
            name="has_voted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="groupparticipant",
            name="is_interested",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="groupparticipant",
            name="is_representative",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="group_vote",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="votes", to="zerver.groupparticipant"
            ),
        ),
        migrations.AlterField(
            model_name="groupparticipant",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_participants",
                to="zerver.group",
            ),
        ),
        migrations.CreateModel(
            name="GroupVote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_votes",
                        to="zerver.group",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.groupparticipant"
                    ),
                ),
                (
                    "vote_for",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_received",
                        to="zerver.groupparticipant",
                    ),
                ),
            ],
        ),
    ]
