# Generated by Django 5.1.7 on 2025-08-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0725_remove_vote_is_interested_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="vote", to="zerver.group"
            ),
        ),
    ]
