# Generated by Django 5.1.7 on 2025-08-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0726_alter_vote_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupvote",
            name="vote_session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_votes",
                to="zerver.vote",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupvote",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_votes",
                to="zerver.group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupvote",
            unique_together={("vote_session", "participant", "vote_for")},
        ),
    ]
