# Generated by Django 5.1.7 on 2025-08-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0727_remove_vote_group_vote_groupvote_vote_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="group_vote",
        ),
    ]
