# Generated by Django 5.1.7 on 2025-08-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0728_remove_vote_group_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="vote_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote",
                to="zerver.message",
            ),
        ),
        migrations.AlterField(
            model_name="groupvote",
            name="vote_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_received",
                to="zerver.groupparticipant",
            ),
        ),
    ]
