# Generated by Django 5.1.7 on 2025-08-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0729_vote_vote_message_alter_groupvote_vote_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupparticipant",
            name="vote_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
