# Generated by Django 5.1.7 on 2025-08-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0730_groupparticipant_vote_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupvote",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_votes",
                to="zerver.group",
            ),
        ),
    ]
