# Generated by Django 5.1.7 on 2025-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0731_alter_groupvote_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="debat",
            name="vote_phase",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
